version: 3.4.{build}
environment:
  TARGET_CONFIGURATION: Release

image: Visual Studio 2022
configuration:
  - Release
platform: Any CPU

pull_requests:
  do_not_increment_build_number: true

branches:
  only:
    - master

before_build:
  - dotnet restore "Thingsboard.Net.sln"

build_script:
  - ps: >-
      dotnet --version

      dotnet pack .\src\Thingsboard.Net.Abstractions\Thingsboard.Net.Abstractions.csproj -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -c %TARGET_CONFIGURATION%

      dotnet pack .\src\Thingsboard.Net.Abstractions\Thingsboard.Net.Flurl.csproj -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -c %TARGET_CONFIGURATION%

      dotnet pack .\src\Thingsboard.Net.Abstractions\Thingsboard.Net.Flurl.DependencyInjection.csproj -p:VersionPrefix=%APPVEYOR_BUILD_VERSION% -c %TARGET_CONFIGURATION%
      
artifacts:
  - path: "src/Thingsboard.Net.*/**/*.nupkg"
    name: "Thingsboard.Net NuGet Packages"
deploy:
  - provider: NuGet
    api_key:
      secure: m281r1dMaWVDTd7j0coGCGUQDUBjgBuvmV1d9iD7ueI1AaME/Xx2t7GK3ox/z4UP
    artifact: /.*\.nupkg/
