version: 3.4.{build}

image: Visual Studio 2022

environment:
  TARGET_CONFIGURATION: Release

platform: Any CPU

branches:
  only:
    - master

only_commits:
  message: /build/
  files:
    - src/*

before_build:
- cmd: >-
    dotnet --version

    dotnet restore "Thingsboard.Net.sln"

build_script:
- cmd: >-
    dotnet pack .\src\Thingsboard.Net.Abstractions\Thingsboard.Net.Abstractions.csproj -c %TARGET_CONFIGURATION%

    dotnet pack .\src\Thingsboard.Net.Flurl\Thingsboard.Net.Flurl.csproj -c %TARGET_CONFIGURATION%

    dotnet pack .\src\Thingsboard.Net.Flurl.DependencyInjection\Thingsboard.Net.Flurl.DependencyInjection.csproj -c %TARGET_CONFIGURATION%      

artifacts:
  - path: "src/**/*.nupkg"
    name: "Thingsboard.Net NuGet Packages"

deploy:
  - provider: NuGet
    api_key:
      secure: m281r1dMaWVDTd7j0coGCGUQDUBjgBuvmV1d9iD7ueI1AaME/Xx2t7GK3ox/z4UP
    artifact: /.*\.nupkg/
